language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t kenshiva/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kenshiva/docker-react npm run test